### ISSUE TITLE
ClassCastException when using Bean Validation API 2.0.0 (or in general: Type Annotations)

### ISSUE THREAD

**Issue by vkennke** [japkit/japkit#23] opened 2018-02-19 13:36 UTC
**Version 1.13**
**JDK 1.8.0_162**

After upgrading a project from Spring Boot 1.5.10 to Spring Boot 2.0.0 RC1 I got the following stack trace:

<pre><code>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project portal-service: Fatal error compiling: java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.sun.tools.javac.code.Type$ArrayType -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project portal-service: Fatal error compiling
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
                at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
                at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
                at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
                at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
                at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
                at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
                at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1086)
                at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
                ... 21 more
Caused by: org.codehaus.plexus.compiler.CompilerException: java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.sun.tools.javac.code.Type$ArrayType
                at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:173)
                at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
                at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1075)
                ... 24 more
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.sun.tools.javac.code.Type$ArrayType
                at com.sun.tools.javac.main.Main.compile(Main.java:553)
                at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
                at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
                at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
                ... 26 more
Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.sun.tools.javac.code.Type$ArrayType
                at com.sun.tools.javac.code.Type$AnnotatedType.getComponentType(Type.java:2018)
                at de.japkit.processor.JavaEmitter._typeRef(JavaEmitter.java:899)
                at de.japkit.processor.JavaEmitter.typeRef(JavaEmitter.java:1381)
                at de.japkit.processor.JavaEmitter.codeForMethod(JavaEmitter.java:720)
                at de.japkit.processor.JavaEmitter._code(JavaEmitter.java:622)
                at de.japkit.processor.JavaEmitter.code(JavaEmitter.java:1333)
                at de.japkit.processor.JavaEmitter.enclosedElementsCode(JavaEmitter.java:948)
                at de.japkit.processor.JavaEmitter.enclosedElementsCode(JavaEmitter.java:941)
                at de.japkit.processor.JavaEmitter.codeForClass(JavaEmitter.java:391)
                at de.japkit.processor.JavaEmitter._code(JavaEmitter.java:288)
                at de.japkit.processor.JavaEmitter.code(JavaEmitter.java:1335)
                at de.japkit.processor.JavaEmitter.compilationUnit(JavaEmitter.java:155)
                at de.japkit.processor.JapkitProcessor.writeSourceFile(JapkitProcessor.java:1146)
                at de.japkit.processor.JapkitProcessor$61.apply(JapkitProcessor.java:989)
                at de.japkit.processor.JapkitProcessor$61.apply(JapkitProcessor.java:982)
                at de.japkit.el.ELSupport.scope(ELSupport.java:168)
                at de.japkit.processor.JapkitProcessor.writeSourceFileAndCommitTypeElement(JapkitProcessor.java:1015)
                at de.japkit.processor.JapkitProcessor$58.accept(JapkitProcessor.java:927)
                at de.japkit.processor.JapkitProcessor$58.accept(JapkitProcessor.java:923)
                at java.util.Map.forEach(Map.java:630)
                at de.japkit.processor.JapkitProcessor.processClassesAndWriteTypeElements(JapkitProcessor.java:938)
                at de.japkit.processor.JapkitProcessor.processLayerAsFarAsPossible(JapkitProcessor.java:543)
                at de.japkit.processor.JapkitProcessor.process(JapkitProcessor.java:345)
                at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
                at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
                at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
                at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
                at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
                at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
                at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
                at com.sun.tools.javac.main.Main.compile(Main.java:523)
                ... 29 more
</pre></code>

**Comment by stefanocke** [comment] 2018-02-19 14:19
Happens only with javac, not with Eclipse jdt.
Could be reproduced by just using Bean Validation API 2.0.0 which comes with Spring Boot 2.0.
See also https://github.com/javaee/hk2/issues/363 for similar issue.

**Comment by stefanocke** [comment] 2018-02-19 14:37
The cause is the implementation of AnnotatedType in javac:

`public static class AnnotatedType extends Type
            implements
               javax.lang.model.type.ArrayType,
               javax.lang.model.type.DeclaredType,
                javax.lang.model.type.PrimitiveType,
                javax.lang.model.type.TypeVariable,
                javax.lang.model.type.WildcardType {`

So basically, if there is an AnnotatedType every "instanceof" is quite useless, since that type is ArrayType and DeclaredType at the same time. Of course getComponentType, it will fail, if the underlying type ist not an ArrayType.
With Bean Validation 2.0, annotations as NotNull can become type annotations. So, for example, method return types become AnnotatedType , if the method (for instance a getter) is annotated with NotNull.

**Comment by stefanocke** [comment] 2018-02-20 18:50
Well, there is even a warning on this in the javadoc of TypeMirror. See https://stackoverflow.com/a/39258562/6265501 ...

**Comment by stefanocke** [comment] 2018-02-24 15:57
@vkennke , this should be mostly fixed in 1.14-SNAPSHOT now. Please give it a try. Maven Repo for snapshots is https://oss.sonatype.org/content/repositories/snapshots

**Closed** 2018-03-03 11:13 UTC
Labels: bug
